### ISSUE TITLE
Update Drupal.Org Issue for Automated Performance Testing

### ISSUE THREAD

**Issue by Allysinning** [tag1consulting/google-drupal#14]
re-open and update old issue to become Planning Issue and have child issues for code
https://www.drupal.org/project/drupal/issues/638078

Change current d.o. issue to focus only on CWV. https://www.drupal.org/project/drupal/issues/3346765

**Comment by catch56** [comment]
Made a start on this: https://www.drupal.org/project/drupal/issues/638078
