### ISSUE TITLE
[Child Issue] Add OpenTelemetry Application Performance Monitoring to core performance tests #3352459

### ISSUE THREAD

**Issue by Allysinning** [tag1consulting/google-drupal#21]
[#3352459: [PP-2] Add OpenTelemetry Application Performance Monitoring to core performance tests](https://www.drupal.org/project/drupal/issues/3352459) send various non-deterministic data to OpenTelemetry for graphs/trends and possibly alerts.

**Comment by catch56** [comment]
This is done.
