### ISSUE TITLE
Collect Performance Notes

### ISSUE THREAD

**Issue by heddn** [tag1consulting/google-drupal#6]
Document here all d.o. issues that are important to performance notes.

Priority performance issues to add performance test coverage for:
https://www.drupal.org/project/drupal/issues/3395776

Issues that are are already fixed to validate against:

https://www.drupal.org/project/drupal/issues/3167034 - lazy loading for responsive images (and/or any other tickets that affect Umami image loading).

https://www.drupal.org/project/drupal/issues/1014086 - cold cache faster ttfb.

https://www.drupal.org/project/drupal/issues/2695871 - one less HTTP request for asset aggregates.

https://www.drupal.org/project/drupal/issues/3327856 - container serialization regression

Issues found or pushed forward during the course of the project:
https://www.drupal.org/project/drupal/issues/3349447 - Umami front page LCP
https://www.drupal.org/project/drupal/issues/3275557 - webp conversion for core's shipped image styles

https://www.drupal.org/node/3309016 => preload image option

**Comment by Allysinning** [comment]
Adding this one to the list too: https://www.drupal.org/project/drupal/issues/3131589

**Comment by catch56** [comment]
My main target now is https://www.drupal.org/project/drupal/issues/3395776 which will be an ideal candidate for assertions on cache gets/sets and database queries.

If we can also add a test for submitting the login form, it might also show a difference on the grafana graphs too.
