### ISSUE TITLE
Plan out work for Automated PHP Core Test Run with CWV in Github

### ISSUE THREAD

**Issue by Allysinning** [tag1consulting/google-drupal#7]
Idea is to have a core phpunit test type that records CWV, later extensible with more things.

Something like this:

1. Try to swap out core's phpunit listener with one that takes CWV from chromedriver - need to make sure this is availabile to phpunit.
2. If that works, pick one or two core tests to use as test cases.
3. Write the the CWV data to either a .csv or json files so it's then possible to pull from elsewhere.

If #1 doesn't work, revisit whole approach - can we make it work via upstream patches or is it a dead end etc?

**Comment by catch56** [comment]
Opened a Drupal core issue for what feels like step 0 here: https://www.drupal.org/project/drupal/issues/3346765
